SELECT 
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    UF_CLIENTE,
    [CPF/CNPJ],
    DATA_NOTA_FISCAL,
    NUM_NOTA_FISCAL,
    DESC_TIPO_OPERACAO,
    FAMILIA_COMERCIAL,
    COD_ITEM,
    DESCR_ITEM,
    QUANTIDADE,
    PESO_BRUTO,
    VALOR,
    DESC_TIPO_OPERACAO
FROM    
    VW_AUDIT_RM_ORDENS_VENDA
WHERE
    COD_ESTABELECIMENTO = 'R631'
    AND DATA_NOTA_FISCAL BETWEEN '2025-12-01' AND '2025-12-31'
    DESC_TIPO_OPERACAO LIKE '%BONIFICACAO%'
