SELECT
    COD_ESTABELECIMENTO,
    SUM(QUANTIDADE) AS QTD_BONIFICADA,
    SUM(VALOR) AS VALOR_BONIFICACAO
FROM    
    VW_AUDIT_RM_ORDENS_VENDA
WHERE
    COD_ESTABELECIMENTO = 'R121'
    AND DATA_NOTA_FISCAL BETWEEN '2025-07-01' AND '2025-12-31'
    AND PARA_FATURAMENTO = 'SIM'
    AND CFOP IN ('1.910', '2.910', '5.910', '6.910')
GROUP BY
    COD_ESTABELECIMENTO
