SELECT  
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    DATEDIFF(DAY, DATA_VENCIMENTO, DATA_LIQUIDACAO) AS DIAS,
    'SIM' AS LIQUIDACAO_ANTES_VENCIMENTO, 
    PERFIL_LANC,
    METODO_PAGAMENTO,
    COMPROVANTE,
    NUM_NOTA_FISCAL,
    PARCELA,
    VALOR_MOEDA,
    VALOR_ORIGINAL,
    STATUS,
    RECID_TRANSACAO,
    TEXTO
FROM    
    VW_AUDIT_RM_TRANSACOES_CLIENTES
WHERE   
    COD_ESTABELECIMENTO = 'R121'
    AND DATA_TRANSACAO BETWEEN '2025-07-07' AND '2026-01-07'
    AND PERFIL_LANC = 'DPC'
    AND DATA_LIQUIDACAO <> '1900-01-01'
    AND DATA_LIQUIDACAO < DATA_VENCIMENTO  -- Filtra apenas antecipadas
