SELECT 
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    DATA_NOTA_FISCAL,
    DATENAME(WEEKDAY, DATA_NOTA_FISCAL) AS DIA_SEMANA,
    NUM_NOTA_FISCAL,
    QUANTIDADE,
    PESO_BIN,
    VALOR
FROM 
    VW_AUDIT_RM_ORDENS_VENDA
WHERE 
    COD_ESTABELECIMENTO = 'R631'
    AND DATA_NOTA_FISCAL BETWEEN '2025-07-01' AND '2025-12-31'
    AND CFOP IN ('5.102', '5.104', '5.106', '5.114', '5.403', '5.405', '5.655', '6.102', '6.108', '6.403', '6.404')
    AND NUM_NOTA_FISCAL NOT LIKE '%EST%'
    AND (
        DATEPART(WEEKDAY, DATA_NOTA_FISCAL) IN (1, 7)  -- Final de semana
        OR DATA_NOTA_FISCAL = EOMONTH(DATA_NOTA_FISCAL)  -- Último dia do mês
    )
