SELECT
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,  
    DATA_TRANSACAO,
    DATA_VENCIMENTO,
    DATA_LIQUIDACAO,
    GETDATE() AS DATA_HOJE,
    DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) AS DIAS_ATRASO,  
    CASE    
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) < 0 THEN 'A Vencer'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 0 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 30 THEN 'Vencidos 0 a 30 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 60 THEN 'Vencidos 31 a 60 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 60 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 90 THEN 'Vencidos 61 a 90 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 90 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 120 THEN 'Vencidos 91 a 120 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 120 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 180 THEN 'Vencidos 121 a 180 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 180 
             AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) <= 360 THEN 'Vencidos de 181 a 360 dias'
        WHEN DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 360 THEN 'Vencidos a mais de 360 dias'
        ELSE 'No Vencimento'
    END AS AGING_BIN,
    PESO_BIN_ABERTO,
    STATUS
FROM    
    VW_AUDIT_RM_ABERTO_BIN
WHERE   
    COD_ESTABELECIMENTO = 'R121'
    AND DATEDIFF(DAY, DATA_VENCIMENTO, GETDATE()) > 30
    AND STATUS = 'ABERTO'
