SELECT
    COD_CLIENTE,
    NOME_CLIENTE,
    -- Somando o PESO por faixa de aging
    SUM(CASE WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) <= 0 THEN PESO_BIN ELSE 0 END) AS [A VENCER],
    SUM(CASE WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) BETWEEN 1 AND 30 THEN PESO_BIN ELSE 0 END) AS [1-30 DIAS],
    SUM(CASE WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) BETWEEN 31 AND 60 THEN PESO_BIN ELSE 0 END) AS [31-60 DIAS],
    SUM(CASE WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) BETWEEN 61 AND 90 THEN PESO_BIN ELSE 0 END) AS [61-90 DIAS],
    SUM(CASE WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) > 90 THEN PESO_BIN ELSE 0 END) AS [MAIS DE 90 DIAS],
    SUM(CASE WHEN DATA_VENCIMENTO IS NULL THEN PESO_BIN ELSE 0 END) AS [SEM DATA],
    -- Total geral por cliente
    SUM(PESO_BIN) AS TOTAL_GERAL,
    -- Contagem de títulos por cliente
    COUNT(*) AS QTDE_TITULOS,
    -- TOTAL DE PESO VENCIDO (soma de todas as faixas exceto "A VENCER")
    SUM(CASE 
        WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) > 0 
        THEN PESO_BIN 
        ELSE 0 
    END) AS TOTAL_PESO_VENCIDO,
    -- TOTAL DE PESO A VENCER (somente faixa "A VENCER")
    SUM(CASE 
        WHEN DATEDIFF(day, DATA_VENCIMENTO, GETDATE()) <= 0 
        THEN PESO_BIN 
        ELSE 0 
    END) AS TOTAL_PESO_A_VENCER
FROM    
    VW_AUDIT_RM_TRANSACOES_BIN
WHERE   
    COD_ESTABELECIMENTO = 'R631'   
GROUP BY
    COD_CLIENTE,
    NOME_CLIENTE
ORDER BY
    COD_CLIENTE
