SELECT
    CLI.DATAAREA_CFS AS COD_ESTABELECIMENTO,
    CLI.STATE AS ESTADO,
    CLI.DISTRICTNAME AS CIDADE,
    CLI.ADDRESS AS ENDERECO,
    CLI.ACCOUNTNUM AS COD_CKIENTE,
    CLI.NAME AS NOME_CLIENTE,
    CC.CLIENTE_DESDE,
    CLI.TIPO,
    CLI.CNPJCPFNUM AS CPF_CNPJ,
    CLI.SEGMENTID,
    CLI.SUBSEGMENTID
FROM    
    VW_BI_CLIENTE AS CLI
LEFT JOIN
    VW_AUDIT_RM_CARTEIRA_CLIENTES AS CC
    ON CLI.DATAAREA_CFS = CC.COD_ESTABELECIMENTO 
    AND CLI.ACCOUNTNUM = CC.COD_CLIENTE
    AND CLI.STATE = CC.ESTADO_CLIENTE
WHERE
    CLI.DATAAREA_CFS = 'R281'
    AND CC.CLIENTE_DESDE BETWEEN '2025-10-01' AND '2025-12-31'
    AND CLI.SEGMENTID = 'SBS99'
    AND CLI.SUBSEGMENTID = '9999'
